# GETTING STARTED WITH NUMPY

### NUMPY

NumPy is a Linear Algebra Library for Python, it is widely used in Data Science with Python because it is incredibly fast and has bindings to C libraries.

Also Numpy has built - in functions and capabilities.

NumPy python's package is for doing math that is more advanced than (+,-,*,/)

This includes special functions like cosine, exponential, sqrt, ...

we can use numpy to generate samples from many types of random variables


To know more about numpy -: https://numpy.org/



In this module we will be covering Numpy basics like Numpy 1-D array , Numpy 2-D array and basic functions and operations 

### Numpy Array

A numpy array is similar to a list. It is fixed in size and elements are of same type. We can cast a list to a numpy array:

Numpy arrays essentially comes in two parts: VECTORS and MATRICES. 
    
Vectors are strictly 1-d arrays and matrices are 2-d (but a matrix can still have one row or one column).

Let's begin by creating NumPy arrays.

In [1]:
import numpy as np

### importing numpy

### NUMPY 1-D Array

In [2]:
lst = [1,2,3,4,5]


In [3]:
''' Created a list '''

' Created a list '

In [4]:
a = np.array(lst)

In [5]:
''' Passes the list to np.array function and store it in a variable a  '''

' Passes the list to np.array function and store it in a variable a  '

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
''' The above list is converted into a array'''

' The above list is converted into a array'

In [8]:
### Check type of a

type(a)

numpy.ndarray

In [9]:
''' Type of a is numpy.ndarray'''

' Type of a is numpy.ndarray'

### ASSIGNING VALUE

#### We can change the first element of the array to 10 as follows:

In [10]:
a
### This is our array

array([1, 2, 3, 4, 5])

In [11]:
a[0] = 10

### Assign the value 10 to the first element

In [12]:
a

array([10,  2,  3,  4,  5])

In [13]:
''' Value of first element of array is changed to 10 '''

' Value of first element of array is changed to 10 '

### SLICING

In [14]:
a[0:4]

array([10,  2,  3,  4])

### Create a 2D Numpy Array


In [15]:
list1 = [[10, 20, 30], [15, 25, 35], [20, 30, 40]]

In [16]:
'''Created a list b, the list contains three nested lists each of equal size'''

'Created a list b, the list contains three nested lists each of equal size'

In [17]:
b = np.array(list1)

In [18]:
b

array([[10, 20, 30],
       [15, 25, 35],
       [20, 30, 40]])

In [19]:
'''Created a matrix'''

'Created a matrix'

#### Checking the Dimension

In [20]:
b.ndim

2

In [21]:
''' Showing b is a 2-D array'''

' Showing b is a 2-D array'

#### Other attributes

In [22]:
b.shape

### 3X3 array

(3, 3)

In [23]:
b.size

9

### Access the element on the third row and first column

In [24]:
b[2,0]

20

In [25]:
# Access the element on the second row and second column

b[1][1]

25

### Basic Operations

In [26]:
# Create a numpy array A

A = np.array([[1, 1], [2, 3]]) 
A

array([[1, 1],
       [2, 3]])

In [27]:
# Create a numpy array B

B = np.array([[2, 2], [3, 4]]) 
B

array([[2, 2],
       [3, 4]])

#### ADD A & B

In [28]:
Z = A + B

In [29]:
Z

array([[3, 3],
       [5, 7]])

Adding a numpy array by another array is simple 

EXAMPLE

<img src = https://numpy.org/devdocs/_images/np_matrix_arithmetic.png >

source  = https://numpy.org/devdocs/_images/np_matrix_arithmetic.png

In [30]:
# Create a numpy array Y

D = np.array([[2, 1], [1, 2]]) 
D

array([[2, 1],
       [1, 2]])

#### MULTIPLICATION

In [31]:
# Multiply D with 2

D = 2 * D
D

array([[4, 2],
       [2, 4]])

In [32]:
''' In this every element of matrix is multiplied by 2'''

' In this every element of matrix is multiplied by 2'

### Built-in Methods


### arange

In [33]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
'''Created a array of 15 elements from 0 to 14'''

'Created a array of 15 elements from 0 to 14'

In [35]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [36]:
'''Created a array of elements from 0 to 16 with step size 2'''

'Created a array of elements from 0 to 16 with step size 2'

### Zeros and Ones
Generate arrays of zeros or ones

In [37]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [38]:
print("Created a 1-D array with 0's")

Created a 1-D array with 0's


In [39]:
np.zeros((4,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
print("Created a 4X4 matrix with 0's")

Created a 4X4 matrix with 0's


In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
print("Created a 1-D array with 1's")

Created a 1-D array with 1's


In [43]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
print("Created a 4X4 matrix with 1's")

Created a 4X4 matrix with 1's


We hav gone through some basic built in functions of NUMPY and learned how to create 1-D array , 2-D arrays and some basic operations.

In next session of Numpy Module we'll be doing some important functions and advanced concepts, till then practice...  